"""
AI explanation layer.

STRICT SEPARATION OF CONCERNS: this module NEVER decides whether a payout
matches. reconcile.py has already made that call deterministically before
anything here runs. Every function in this file receives the engine's
decision as an input and produces a plain-English narration of it -- it
is not permitted to override, second-guess, or silently "correct" a
status.

Every explanation is built from exactly two labeled sections:
  FACT                -- verbatim numbers/ids the reconciliation engine
                          produced. Never generated by the AI.
  POSSIBLE EXPLANATION -- a hypothesis for the gap. Always hedged
                          ("could indicate", "may reflect"), never
                          presented as confirmed fact.

Works with zero configuration: LLM_MODE=mock (the default, see
config.py / .env.example) produces deterministic, rule-based
explanations with no network calls and no API key. LLM_MODE=live calls
the Anthropic API and falls back to the mock explanation -- clearly
labeled as a fallback -- if the API key is missing, the call fails, or
the response is malformed. The dashboard and reports work identically
either way.

Every explanation request is appended to output/audit_log.jsonl (see
log_audit()) so a judge can trace ORDER DATA -> DETERMINISTIC MATCHING ->
FINANCIAL RESULT -> AI EXPLANATION for any payout.
"""

import hashlib
import json
import re
import time
from datetime import datetime, timezone
from pathlib import Path

import config
from money import format_inr

CLOSE_MATCH_CAUSES = [
    "an unlogged payout-processing fee charged by the payment rail",
    "a small manual adjustment applied at settlement time",
    "a rounding or currency-conversion difference introduced during payout batching",
    "a minor refund or partial refund that was applied after the order ledger was last updated",
]

UNRESOLVED_CAUSES_WITH_CANDIDATE = [
    "a manual adjustment or correction not tied to any single order",
    "a chargeback reversal credited back through this payout",
    "one or more orders that have not yet appeared in the order ledger (late-arriving orders)",
    "a refund recorded in the payout rail but not yet reflected against the relevant order(s)",
]

UNRESOLVED_CAUSES_NO_CANDIDATE = [
    "a payout entirely unrelated to this seller's order ledger, such as a standalone chargeback reversal or manual correction",
    "all of this seller's genuinely relevant orders having already been consumed by another payout, leaving nothing eligible to compare against",
    "the orders that fund this payout not having arrived in the ledger yet",
]

PAYOUT_ID_PATTERN = re.compile(r"PYT-\d{4,6}", re.IGNORECASE)


def _stable_index(key: str, n: int) -> int:
    """Deterministic pseudo-random index from a string key, so mock
    explanations vary across payouts but are 100% reproducible."""
    digest = hashlib.sha256(key.encode("utf-8")).hexdigest()
    return int(digest, 16) % n


def _build_fact_close_match(result: dict) -> str:
    payout_amt = format_inr(result["payout_amount_paise"])
    candidate_amt = format_inr(result["matched_total_paise"])
    delta_paise = result["delta_paise"]
    direction = "short by" if delta_paise > 0 else "over by"
    delta_amt = format_inr(abs(delta_paise))
    order_ids = ", ".join(result["matched_order_ids"]) or "(none)"
    return (
        f"Payout {result['payout_id']} for seller {result['seller_id']} is {payout_amt}. "
        f"The closest matching combination of eligible orders ({order_ids}) sums to "
        f"{candidate_amt}. The deterministic reconciliation engine found this within its "
        f"configured tolerance of {format_inr(result['tolerance_paise'])}, but it is "
        f"{direction} {delta_amt}."
    )


def _build_fact_unresolved(result: dict) -> str:
    payout_amt = format_inr(result["payout_amount_paise"])
    n_eligible = len(result["eligible_order_ids"])
    if result["matched_order_ids"]:
        candidate_amt = format_inr(result["matched_total_paise"])
        delta_amt = format_inr(abs(result["delta_paise"])) if result["delta_paise"] is not None else "unknown"
        candidate_clause = (
            f"The closest combination found ({', '.join(result['matched_order_ids'])}) "
            f"sums to {candidate_amt}, a gap of {delta_amt} -- outside the configured "
            f"tolerance of {format_inr(result['tolerance_paise'])}."
        )
    else:
        candidate_clause = "No combination of eligible orders came within a comparable range at all."
    return (
        f"Payout {result['payout_id']} for seller {result['seller_id']} is {payout_amt}. "
        f"{n_eligible} order(s) were eligible for this payout's seller and date window. "
        f"{candidate_clause}"
    )


def _mock_explain_close_match(result: dict) -> str:
    idx = _stable_index(result["payout_id"] + "close", len(CLOSE_MATCH_CAUSES))
    cause = CLOSE_MATCH_CAUSES[idx]
    delta_amt = format_inr(abs(result["delta_paise"]))
    return (
        f"POSSIBLE EXPLANATION: The {delta_amt} gap could indicate {cause}. "
        f"This is a hypothesis based on the size of the gap, not a confirmed cause -- "
        f"it should be verified against the seller's settlement statement before being "
        f"written off."
    )


def _mock_explain_unresolved(result: dict) -> str:
    has_candidate = bool(result["matched_order_ids"])
    causes = UNRESOLVED_CAUSES_WITH_CANDIDATE if has_candidate else UNRESOLVED_CAUSES_NO_CANDIDATE
    idx = _stable_index(result["payout_id"] + "unresolved", len(causes))
    cause = causes[idx]
    return (
        f"POSSIBLE EXPLANATION: This payout could not be explained within tolerance. "
        f"A likely cause is {cause}. "
        f"This is a hypothesis, not a confirmed cause -- it should be investigated "
        f"manually against the seller's payout statement and any manual adjustment logs."
    )


def _call_live_llm(fact_text: str, question: str = None) -> str:
    """Call the Anthropic API. Raises on any failure -- caller handles fallback."""
    import anthropic  # imported lazily so mock mode never requires the package

    if not config.ANTHROPIC_API_KEY:
        raise RuntimeError("ANTHROPIC_API_KEY is not set")

    client = anthropic.Anthropic(api_key=config.ANTHROPIC_API_KEY, timeout=config.LLM_TIMEOUT_SECONDS)

    system_prompt = (
        "You are a financial exception-explanation assistant for a marketplace payout "
        "reconciliation system. A deterministic reconciliation engine has ALREADY decided "
        "whether a payout matches its orders -- you are not deciding that and must not "
        "contradict it. You will be given FACTS (verbatim reconciliation evidence). "
        "Respond with a single short paragraph, prefixed exactly with "
        "'POSSIBLE EXPLANATION:', suggesting a plausible, clearly-hedged hypothesis for "
        "the discrepancy (e.g. 'could indicate', 'may reflect'). Never state a cause as "
        "certain. Never invent order IDs, amounts, or transactions that are not present "
        "in the FACTS given to you. Keep it under 80 words."
    )

    user_content = f"FACTS:\n{fact_text}"
    if question:
        user_content += f"\n\nUser question: {question}"

    response = client.messages.create(
        model=config.LLM_MODEL,
        max_tokens=config.LLM_MAX_TOKENS,
        system=system_prompt,
        messages=[{"role": "user", "content": user_content}],
    )

    text_parts = [block.text for block in response.content if getattr(block, "type", None) == "text"]
    text = "\n".join(text_parts).strip()
    if not text:
        raise RuntimeError("LLM returned an empty or malformed response")
    return text


def log_audit(entry: dict):
    config.OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    # Defense in depth: never let a secret reach the audit trail even if a
    # future caller accidentally includes one in the entry dict.
    safe_entry = {k: v for k, v in entry.items() if "key" not in k.lower() and "secret" not in k.lower()}
    with open(config.AUDIT_LOG_JSONL, "a") as f:
        f.write(json.dumps(safe_entry) + "\n")


def explain_payout(result: dict, question: str = None) -> dict:
    """Generate an explanation for a CLOSE_MATCH or UNRESOLVED payout result.

    Returns:
      {
        "payout_id", "status", "fact", "explanation", "mode", "model"
      }
    `mode` is one of "mock", "live", or "mock_fallback" (live was
    requested but failed, so mock was used instead).

    Calling this on a MATCHED payout is a no-op that returns a fact-only
    response with no AI call -- the AI layer is intentionally never
    exercised on payouts the engine already fully explained.
    """
    status = result["status"]

    if status == "MATCHED":
        fact = (
            f"Payout {result['payout_id']} is fully explained by orders "
            f"{', '.join(result['matched_order_ids'])} with zero delta. No exception, "
            f"no AI explanation needed."
        )
        return {
            "payout_id": result["payout_id"],
            "status": status,
            "fact": fact,
            "explanation": None,
            "mode": "n/a",
            "model": None,
        }

    fact = _build_fact_close_match(result) if status == "CLOSE_MATCH" else _build_fact_unresolved(result)

    mode = "mock"
    model = None
    explanation = None
    error = None

    if config.LLM_MODE == "live":
        try:
            explanation = _call_live_llm(fact, question=question)
            mode = "live"
            model = config.LLM_MODEL
        except Exception as exc:  # noqa: BLE001 -- must degrade gracefully, not crash the pipeline
            error = str(exc)
            mode = "mock_fallback"

    if explanation is None:
        explanation = (
            _mock_explain_close_match(result) if status == "CLOSE_MATCH" else _mock_explain_unresolved(result)
        )
        model = "mock-rule-based"

    entry = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "payout_id": result["payout_id"],
        "reconciliation_status": status,
        "question": question,
        "fact": fact,
        "model": model,
        "mode": mode,
        "output": explanation,
    }
    if error:
        entry["fallback_reason"] = error
    log_audit(entry)

    return {
        "payout_id": result["payout_id"],
        "status": status,
        "fact": fact,
        "explanation": explanation,
        "mode": mode,
        "model": model,
    }


def extract_payout_id(question: str) -> str:
    match = PAYOUT_ID_PATTERN.search(question or "")
    return match.group(0).upper() if match else None


def answer_question(question: str, results_by_id: dict) -> dict:
    """Q&A entry point: 'why doesn't payout PYT-2291 fully match?'

    `results_by_id` maps payout_id -> reconciliation result dict (as
    produced by reconcile.reconcile()). Never invents a payout, order, or
    number that isn't present in that evidence.
    """
    question = (question or "").strip()
    if not question:
        return {"ok": False, "message": "Please type a question, e.g. \"Why doesn't payout PYT-00042 fully match?\""}

    payout_id = extract_payout_id(question)
    if not payout_id:
        return {
            "ok": False,
            "message": (
                "I couldn't find a payout ID in your question. Please reference one "
                "directly, e.g. \"Why doesn't payout PYT-00042 fully match?\""
            ),
        }

    result = results_by_id.get(payout_id)
    if result is None:
        return {"ok": False, "message": f"No payout with ID {payout_id} exists in this dataset."}

    explanation = explain_payout(result, question=question)
    return {"ok": True, "payout_id": payout_id, **explanation}


def explain_all_exceptions(results: list) -> dict:
    """Run explain_payout for every CLOSE_MATCH/UNRESOLVED result.
    Returns {payout_id: explanation_dict}.
    """
    out = {}
    for r in results:
        if r["status"] in ("CLOSE_MATCH", "UNRESOLVED"):
            out[r["payout_id"]] = explain_payout(r)
    return out


def main():
    """CLI smoke test: explain every exception in the last reconciliation run."""
    if not config.RECONCILIATION_RESULTS_JSON.exists():
        print("No reconciliation results found. Run reconcile.py first.")
        return
    with open(config.RECONCILIATION_RESULTS_JSON) as f:
        outcome = json.load(f)

    explanations = explain_all_exceptions(outcome["results"])
    print(f"Generated {len(explanations)} explanations (LLM_MODE={config.LLM_MODE}).")
    for payout_id, exp in list(explanations.items())[:3]:
        print(f"\n{payout_id} [{exp['status']}] (mode={exp['mode']})")
        print(f"  {exp['fact']}")
        print(f"  {exp['explanation']}")


if __name__ == "__main__":
    main()
